slice_name: Treemap
description: null
certified_by: null
certification_details: null
viz_type: treemap_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  groupby:
  - region
  - country_code
  limit: '25'
  markup_type: markdown
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  until: now
  viz_type: treemap_v2
  metric: sum__SP_POP_TOTL
  adhoc_filters:
  - clause: WHERE
    subject: year
    operator: TEMPORAL_RANGE
    comparator: '2014-01-01 : 2014-01-02'
    expressionType: SIMPLE
  form_data_bak:
    compare_lag: '10'
    compare_suffix: o10Y
    country_fieldtype: cca3
    entity: country_code
    granularity_sqla: year
    groupby:
    - region
    - country_code
    limit: '25'
    markup_type: markdown
    metrics:
    - sum__SP_POP_TOTL
    row_limit: 50000
    show_bubbles: true
    since: '1960-01-01'
    time_range: '2014-01-01 : 2014-01-02'
    until: now
    viz_type: treemap
query_context: null
cache_timeout: null
uuid: a30d7644-0140-42c5-8ca3-5255cc6f50b9
version: 1.0.0
dataset_uuid: 2ebaf597-6bb6-4e1a-b3dd-f2d808bdd1ce
