slice_name: World's Population
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  compare_lag: '10'
  compare_suffix: over 10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 50000
  show_bubbles: true
  since: '2000'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: big_number
query_context: null
cache_timeout: null
uuid: 6b502707-78ee-455a-9109-da5e2c75678f
version: 1.0.0
dataset_uuid: 2ebaf597-6bb6-4e1a-b3dd-f2d808bdd1ce
